const MoviesTypes = {
  FETCH_START: 'FECTH_MOVIES_START',
  FETCH_SUCCESS: 'FECTH_MOVIES_SUCCESS',
  FETCH_MORE: 'FECTH_MOVIES_MORE',
  FETCH_FAILURE: 'FECTH_MOVIES_FAILURE',
}

export default MoviesTypes